# Generated by Django 5.0.6 on 2024-06-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blackjack_wins",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="poker_wins",
            field=models.IntegerField(default=0),
        ),
    ]
