# Generated by Django 5.0.6 on 2024-06-05 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blackjack", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
